name: test Odoo addons

on:
  pull_request:
    branches:
      - "12.0*"
  push:
    branches:
      - "12.0*"

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py3.6-odoo12.0:latest
            makepot: "true"
          - container: ghcr.io/oca/oca-ci/py3.6-ocb12.0:latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Initialize test db
        run: oca_init_test_database
      - name: Pip install PR
        run: pip3 install -e "git+https://github.com/sergiocorato/mis-builder@12.0-imp-mis_builder-query-drilldown-filtered#egg=odoo12-addon-mis_builder&subdirectory=setup/mis_builder"
      - name: Run tests
        run: oca_run_tests
